stages:
  - build
  - test
  - deploy


build_py37:
    stage: build
    tags:
        - linux
    image: python:3.7-stretch
    before_script:
        - python -m pip install --upgrade pip
        - pip install --upgrade setuptools wheel
    script:
        - python setup.py sdist bdist_wheel
    artifacts:
        paths:
            - dist/
        when: on_success
        expire_in: 4h

test_wheel_py37:
    stage: test
    tags:
        - linux
    image: python:3.7-stretch
    before_script:
        - python -m pip install --upgrade pip
        - pip install --pre dist/*.whl
    script:
        - mkdir tmp
        - cd tmp
        - python -m pypolynom.test


test_tarball_py37:
    stage: test
    tags:
        - linux
    image: python:3.7-stretch
    before_script:
        - python -m pip install --upgrade pip
        - pip install --pre dist/*.tar.gz
    script:
        - mkdir tmp
        - cd tmp
        - python -m pypolynom.test
        - cd ..


pages:
    stage: deploy
    tags:
        - linux
    image: debian:stable
    before_script:
        - apt-get update
        - apt-get install tree
    script:
        - rm -rf public
        - mkdir -p public
        - cp dist/* public
        - cd public
        - tree -H '.' -h -T 'pypolynom' --noreport --charset utf-8 -o index.html
        - ls -Rl
    artifacts:
        paths:
            - public
        expire_in: 4h
    only:
        - master
