stages:
  - build
  - test
  - doc
  - deploy


build_py37:
    stage: build
    tags:
        - linux
    image: quay.io/pypa/manylinux1_x86_64
    before_script:
        - export PATH=/opt/python/cp37-cp37m/bin/:${PATH}
        - python -m pip install --upgrade pip
        - pip install --upgrade setuptools wheel cython
    script:
        - python setup.py sdist bdist_wheel
        # Run auditwheel (not needed for this project)
        - mkdir tmp
        - mv dist/*.whl tmp/
        - for WHEEL in tmp/*.whl; do
              auditwheel repair "${WHEEL}" -w dist/;
          done
    artifacts:
        paths:
            - dist/
        when: on_success
        expire_in: 4h


test_wheel_py37:
    stage: test
    tags:
        - linux
    image: python:3.7-stretch
    before_script:
        - python -m pip install --upgrade pip
        - pip install --pre dist/*.whl
    script:
        - mkdir tmp; cd tmp
        - python -m unittest pypolynom.test.suite_without_gui


test_tarball_py37:
    stage: test
    tags:
        - linux
    image: python:3.7-stretch
    before_script:
        - python -m pip install --upgrade pip
        - pip install --pre dist/*.tar.gz
    script:
        - mkdir tmp; cd tmp
        - python -m unittest pypolynom.test.suite_without_gui


build_doc_with_wheel:
    stage: doc
    tags:
        - linux
    image: docker-registry.esrf.fr/dau/tomwer:python3.5_stretch_pyqt5
    before_script:
        - apt-get update && apt-get -y upgrade
        - apt-get install --yes --force-yes pandoc
        - python -m pip install --upgrade pip
        - pip install --pre --find-links dist/ pypolynom[doc]
    script:
        - /usr/bin/xvfb-run --server-args="-screen 0 1024x768x24" -a python setup.py build_sphinx -b html
        - mv build/sphinx/html .
    artifacts:
        paths:
            - html
        when: on_success
        expire_in: 4h

pages:
    stage: deploy
    tags:
        - linux
    image: debian:stable
    before_script:
        - apt-get update
        - apt-get install tree
    script:
        - rm -rf public; mkdir -p public
        - cp dist/* public
        - mv html public/doc
        - cd public
        - tree -H '.' -L 1 -h -T 'pypolynom' --noreport --charset utf-8 -o index.html
        - ls -Rl
    artifacts:
        paths:
            - public
        expire_in: 4h
    only:
        - master
