dist: xenial
language: python
os: linux

matrix:
    include:
        - python: 3.6
        - python: 3.7

before_install:
    # Upgrade/install distribution and "setup_requires" modules
    - python -m pip install --upgrade pip
    - pip install --upgrade setuptools wheel cython

install:
    # Generate source archive and wheel
    - python setup.py sdist
    - python setup.py bdist_wheel
    - ls dist

before_script:
    # Install wheel package
    - pip install --pre dist/pypolynom*.whl

script:
    # Run the tests on the installed version
    # Change directory in order to avoid importing from the source
    - mkdir tmp; cd tmp
    - python -m unittest pypolynom.test.suite_without_gui
