dist: xenial
language: python

matrix:
    include:
        - python: 3.6
          os: linux

        - python: 3.7
          os: linux

before_install:
    # Upgrade distribution modules
    - python -m pip install --upgrade pip
    - pip install --upgrade setuptools wheel

install:
    # Generate source archive and wheel
    - python setup.py sdist
    - python setup.py bdist_wheel
    - ls dist

before_script:
    # Install wheel package
    - pip install --pre dist/pypolynom*.whl

script:
    # Run the tests on the source tree directly
    - python -m unittest pypolynom

    # Run the tests on the installed version
    # Change directory in order to avoid importing from the source
    - mkdir tmp
    - cd tmp
    - python -m pypolynom.test
